# Generated by Django 5.2.10 on 2026-01-19 02:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artistas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#1DB954', max_length=7)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_albums/')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('artistas', models.ManyToManyField(related_name='albums', to='music.artista')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-fecha_lanzamiento', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('minutos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('segundos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_canciones/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='musica/')),
                ('reproducciones', models.PositiveIntegerField(default=0)),
                ('favorita', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='music.album')),
                ('artistas', models.ManyToManyField(related_name='canciones', to='music.artista')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-fecha_subida', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_oscuro', models.BooleanField(default=True)),
                ('calidad_audio', models.CharField(choices=[('low', 'Baja (128kbps)'), ('medium', 'Media (192kbps)'), ('high', 'Alta (320kbps)')], default='high', max_length=10)),
                ('volumen_default', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('shuffle_default', models.BooleanField(default=False)),
                ('repeat_default', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuarios', to='music.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='CancionGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='music.cancion')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genero')),
            ],
            options={
                'verbose_name': 'Género de Canción',
                'verbose_name_plural': 'Géneros de Canciones',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('publica', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('canciones', models.ManyToManyField(blank=True, related_name='playlists', to='music.cancion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='music.cancion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reproducción',
                'verbose_name_plural': 'Reproducciones',
                'ordering': ['-fecha_reproduccion'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-fecha_lanzamiento'], name='music_album_fecha_l_e8c628_idx'),
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['-fecha_subida'], name='music_canci_fecha_s_dc4180_idx'),
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['favorita'], name='music_canci_favorit_e9b6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['activa'], name='music_canci_activa_f6edf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cancion',
            unique_together={('titulo', 'archivo')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'cancion')},
        ),
        migrations.AlterUniqueTogether(
            name='canciongenero',
            unique_together={('cancion', 'genero')},
        ),
        migrations.AddIndex(
            model_name='reproduccion',
            index=models.Index(fields=['-fecha_reproduccion'], name='music_repro_fecha_r_f3ca9d_idx'),
        ),
    ]
